//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HospitalDbContext : DbContext
    {
        public HospitalDbContext()
            : base("name=HospitalDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Accounts { get; set; }
        public DbSet<ConsultationCategory> ConsultationCategories { get; set; }
        public DbSet<ConsultationEstimate> ConsultationEstimates { get; set; }
        public DbSet<ConsultationSample> ConsultationSamples { get; set; }
        public DbSet<Dating> Datings { get; set; }
        public DbSet<Form> Forms { get; set; }
        public DbSet<LaboratoryCategory> LaboratoryCategories { get; set; }
        public DbSet<LaboratoryEstimate> LaboratoryEstimates { get; set; }
        public DbSet<LaboratorySample> LaboratorySamples { get; set; }
        public DbSet<Management> Managements { get; set; }
        public DbSet<MedicalHistory> MedicalHistories { get; set; }
        public DbSet<MedicalImagingCategory> MedicalImagingCategories { get; set; }
        public DbSet<MedicalImagingEstimate> MedicalImagingEstimates { get; set; }
        public DbSet<MedicalImagingSample> MedicalImagingSamples { get; set; }
        public DbSet<MedicalRecord> MedicalRecords { get; set; }
        public DbSet<Patient> Patients { get; set; }
        public DbSet<PrescriptionCategory> PrescriptionCategories { get; set; }
        public DbSet<PrescriptionEstimate> PrescriptionEstimates { get; set; }
        public DbSet<PrescriptionSample> PrescriptionSamples { get; set; }
        public DbSet<Referrer> Referrers { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TempManagement> TempManagements { get; set; }
        public DbSet<TempWait> TempWaits { get; set; }
        public DbSet<TempWaitingList> TempWaitingLists { get; set; }
        public DbSet<VariousDocumentCategory> VariousDocumentCategories { get; set; }
        public DbSet<VariousDocumentEstimate> VariousDocumentEstimates { get; set; }
        public DbSet<VariousDocumentSample> VariousDocumentSamples { get; set; }
        public DbSet<Visit> Visits { get; set; }
        public DbSet<WaitingList> WaitingLists { get; set; }
        public DbSet<Worker> Workers { get; set; }
    }
}
