//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        public Patient()
        {
            this.Datings = new HashSet<Dating>();
            this.MedicalRecords = new HashSet<MedicalRecord>();
            this.Visits = new HashSet<Visit>();
            this.WaitingLists = new HashSet<WaitingList>();
            this.MedicalHistories = new HashSet<MedicalHistory>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public short Age { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public Nullable<short> Weight { get; set; }
        public Nullable<short> Height { get; set; }
    
        public virtual ICollection<Dating> Datings { get; set; }
        public virtual ICollection<MedicalRecord> MedicalRecords { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
        public virtual ICollection<WaitingList> WaitingLists { get; set; }
        public virtual ICollection<MedicalHistory> MedicalHistories { get; set; }
    }
}
