//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempManagement
    {
        public string Id { get; set; }
        public string WorkerId { get; set; }
        public string Forms { get; set; }
        public string Services { get; set; }
        public string Categorys { get; set; }
        public bool Status { get; set; }
    }
}
