//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class VariousDocumentEstimateEditHistory
    {
        public int Id { get; set; }
        public int EstimateId { get; set; }
        public int WorkerId { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual VariousDocumentEstimate VariousDocumentEstimate { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
