//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaitingList
    {
        public WaitingList()
        {
            this.ConsultationCategories = new HashSet<ConsultationCategory>();
            this.LaboratoryCategories = new HashSet<LaboratoryCategory>();
            this.MedicalImagingCategories = new HashSet<MedicalImagingCategory>();
            this.PrescriptionCategories = new HashSet<PrescriptionCategory>();
            this.VariousDocumentCategories = new HashSet<VariousDocumentCategory>();
        }
    
        public string Id { get; set; }
        public string PatientId { get; set; }
        public System.TimeSpan Time { get; set; }
    
        public virtual Patient Patient { get; set; }
        public virtual ICollection<ConsultationCategory> ConsultationCategories { get; set; }
        public virtual ICollection<LaboratoryCategory> LaboratoryCategories { get; set; }
        public virtual ICollection<MedicalImagingCategory> MedicalImagingCategories { get; set; }
        public virtual ICollection<PrescriptionCategory> PrescriptionCategories { get; set; }
        public virtual ICollection<VariousDocumentCategory> VariousDocumentCategories { get; set; }
    }
}
