//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Accounts = new HashSet<Account>();
            this.ConsultationEstimates = new HashSet<ConsultationEstimate>();
            this.ConsultationEstimates1 = new HashSet<ConsultationEstimate>();
            this.Datings = new HashSet<Dating>();
            this.LaboratoryEstimates = new HashSet<LaboratoryEstimate>();
            this.LaboratoryEstimates1 = new HashSet<LaboratoryEstimate>();
            this.MedicalImagingEstimates = new HashSet<MedicalImagingEstimate>();
            this.MedicalImagingEstimates1 = new HashSet<MedicalImagingEstimate>();
            this.PrescriptionEstimates = new HashSet<PrescriptionEstimate>();
            this.PrescriptionEstimates1 = new HashSet<PrescriptionEstimate>();
            this.VariousDocumentEstimates = new HashSet<VariousDocumentEstimate>();
            this.VariousDocumentEstimates1 = new HashSet<VariousDocumentEstimate>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public System.DateTime DOB { get; set; }
        public short Age { get; set; }
        public string Address { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Email { get; set; }
        public string Position { get; set; }
        public Nullable<int> Salary { get; set; }
        public Nullable<System.DateTime> StartWorkDate { get; set; }
    
        public virtual ICollection<Account> Accounts { get; set; }
        public virtual ICollection<ConsultationEstimate> ConsultationEstimates { get; set; }
        public virtual ICollection<ConsultationEstimate> ConsultationEstimates1 { get; set; }
        public virtual ICollection<Dating> Datings { get; set; }
        public virtual ICollection<LaboratoryEstimate> LaboratoryEstimates { get; set; }
        public virtual ICollection<LaboratoryEstimate> LaboratoryEstimates1 { get; set; }
        public virtual ICollection<MedicalImagingEstimate> MedicalImagingEstimates { get; set; }
        public virtual ICollection<MedicalImagingEstimate> MedicalImagingEstimates1 { get; set; }
        public virtual ICollection<PrescriptionEstimate> PrescriptionEstimates { get; set; }
        public virtual ICollection<PrescriptionEstimate> PrescriptionEstimates1 { get; set; }
        public virtual ICollection<VariousDocumentEstimate> VariousDocumentEstimates { get; set; }
        public virtual ICollection<VariousDocumentEstimate> VariousDocumentEstimates1 { get; set; }
        public virtual Account Account { get; set; }
    }
}
